pipeline:
  name: myapp-full-ci-cd-pipeline
  identifier: myappfullcicdpipeline
  projectIdentifier: Harness
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: harnessjavademo
        repoName: harness-java-demo
        build: <+input>
  stages:
    - stage:
        name: ci-build
        identifier: mavenbuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: false
            paths: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          buildIntelligence:
            enabled: false
          execution:
            steps:
              - step:
                  type: Run
                  name: maven-build
                  identifier: mavenbuild
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.9.9-eclipse-temurin-17
                    shell: Sh
                    command: mvn clean verify
              - step:
                  name: docker-build-and-push
                  identifier: dockerbuildandpush
                  template:
                    templateRef: dockerbuildandpush
                    versionLabel: "1"
    - stage:
        name: myApp-Dev-CD-Deployment
        identifier: myAppDevCDDeployment
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: dev
            serviceInputs:
              serviceDefinition:
                type: NativeHelm
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: Dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: Dev
          execution:
            steps:
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  allowStageExecutions: true
  fixedInputsOnRerun: false
