pipeline:
  name: myapp-full-ci-cd-pipeline
  identifier: myappfullcicdpipeline
  projectIdentifier: Harness
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: harnessjavademo
        repoName: harness-java-demo
        build: <+input>
  stages:
    - stage:
        name: ci-build
        identifier: mavenbuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: false
            paths: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          buildIntelligence:
            enabled: false
          execution:
            steps:
              - step:
                  type: Run
                  name: maven-build
                  identifier: mavenbuild
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.9.9-eclipse-temurin-17
                    shell: Sh
                    command: |-
                      pwd
                      ls -latr
                      mvn -v
                      mvn clean verify
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerImage
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: dockekroy/harness-java-demo
                    tags:
                      - <+pipeline.sequenceId>
