service:
  name: dev
  identifier: dev
  orgIdentifier: default
  projectIdentifier: Harness
  serviceDefinition:
    spec:
      manifests:
        - manifest:
            identifier: prod
            type: HelmChart
            spec:
              store:
                type: Github
                spec:
                  connectorRef: harnessjavademo
                  gitFetchType: Branch
                  folderPath: helm-charts
                  repoName: harness-java-demo
                  branch: main
              subChartPath: ""
              valuesPaths:
                - helm-charts/values.yaml
                - helm-charts/values-dev.yaml
              optionalValuesYaml: false
              skipResourceVersioning: false
              enableDeclarativeRollback: false
              helmVersion: V3
              fetchHelmChartMetadata: false
      artifacts:
        primary:
          primaryArtifactRef: dev
          sources:
            - spec:
                connectorRef: harnessjavademodocker
                imagePath: dockekroy/harness-java-demo
                tag: <+pipeline.stages.Identifyglobalversion.spec.execution.steps.ShellScript_1.output.outputVariables.global_version>
                digest: ""
              identifier: dev
              type: DockerRegistry
    type: NativeHelm
