infrastructureDefinition:
  name: prod
  identifier: prod
  orgIdentifier: default
  projectIdentifier: Harness
  environmentRef: Prod
  deploymentType: NativeHelm
  type: KubernetesDirect
  spec:
    connectorRef: harnessdemocluster
    namespace: harness-demo-prod
    releaseName: myapp
  allowSimultaneousDeployments: false
